TARGET_NO_BOOTLOADER := true
TARGET_ARCH := arm

TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a9
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_SMP := true

TARGET_USERIMAGES_USE_EXT4 := true
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1073741824
#BOARD_USERDATAIMAGE_PARTITION_SIZE :=
#BOARD_CACHEIMAGE_PARTITION_SIZE :=
#BOARD_CACHE_IMAGE_FILE_SYTEM_TYPE := ext4
BOARD_FLASH_BLOCK_SIZE := 4096

